export {default as About} from './About'
export {default as Camera} from './Camera'
export {default as Game1} from './Game1'
export {default as Game2} from './Game2'
export {default as GameSelect} from './GameSelect'
export {default as GameInit} from './GameInit'
export {default as GameItem} from './GameItem'
export {default as Home} from './Home'
